
language: python
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:jokva/carolina'
    packages:
      - libboost-python-dev
      - libboost-all-dev

matrix:
    include:
      - dist: trusty
        python: 2.7
        env: PY3=no
      - dist: trusty
        python: 3.4
        env: 
           - BOOST_PYTHON=boost_python-py34
           - PY3=yes
      - dist: xenial
        python: 3.5
        env: 
           - BOOST_PYTHON=boost_python-py35
           - PY3=yes
      - dist: xenial
        python: 3.6
        env: 
           - BOOST_PYTHON=boost_python-py35
           - PY3=yes
      - dist: xenial
        python: 3.7
        env: 
           - BOOST_PYTHON=boost_python-py35
           - PY3=yes

script:
  - echo "Running build and tests against $(python --version) ..."
  - if [[ ${PY3} == yes ]]; then sudo apt-get install python3-dakota1 python3-libdakota-dev; fi
  - if [[ ${PY3} == no ]]; then sudo apt-get install dakota1 libdakota-dev; fi

  - ./setup.py build
  - ./setup.py test

